/*
 * SPDX-FileCopyrightText: 2022-2024 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_LOTTIE_ASSETS_FILES           1
#define MMAP_LOTTIE_ASSETS_CHECKSUM        0xF6B2

enum MMAP_LOTTIE_ASSETS_LISTS {
    MMAP_LOTTIE_ASSETS_THINK_JSON = 0,        /*!< think.json */
};
